=== anthonywachs/PacIFiC/GRAINS_V1/Main/dtd/Grains2D.dtd
<!-- Grains2D DTD -->

<!ENTITY % Convex.dtd SYSTEM "/home/wachs/Multiphase/PacNewGrains-Git/pacific/GRAINS_V1/Main/dtd/Convex.dtd">
%Convex.dtd;

<!ENTITY % Contact.dtd SYSTEM "/home/wachs/Multiphase/PacNewGrains-Git/pacific/GRAINS_V1/Main/dtd/Contact.dtd">
%Contact.dtd;

<!ELEMENT Point EMPTY>
<!ATTLIST Point X CDATA #REQUIRED>
<!ATTLIST Point Y CDATA #REQUIRED>
<!ATTLIST Point Z CDATA #REQUIRED>

<!ELEMENT Centre EMPTY>
<!ATTLIST Centre X CDATA #REQUIRED>
<!ATTLIST Centre Y CDATA #REQUIRED>
<!ATTLIST Centre Z CDATA #REQUIRED>

<!ELEMENT Vecteur EMPTY>
<!ATTLIST Vecteur X CDATA #REQUIRED>
<!ATTLIST Vecteur Y CDATA #REQUIRED>
<!ATTLIST Vecteur Z CDATA #REQUIRED>


<!ELEMENT Grains2D (Construction, Forces, Simulation)>
<!ATTLIST Grains2D Type (Standard|MPI) "Standard">

  <!ELEMENT Construction (Recipient, DomainDecomposition?, MPI?, Contacts, 
  		 Particules?, Obstacles?, Reload?, Periode?,
		 ContactsParticuleObstacle?)>
    <!ELEMENT Recipient EMPTY>
    <!ATTLIST Recipient LX CDATA #REQUIRED>
    <!ATTLIST Recipient LY CDATA #REQUIRED>
    <!ATTLIST Recipient LZ CDATA #REQUIRED>

    <!ELEMENT DomainDecomposition EMPTY>
    <!ATTLIST DomainDecomposition NX CDATA #REQUIRED>
    <!ATTLIST DomainDecomposition NY CDATA #REQUIRED>

    <!ELEMENT MPI EMPTY>
    <!ATTLIST MPI Strategie (AllgatherGlobal|AllgatherLocal|SRLocal
    	|SRLocalCommFirst|SRLocalCommOpt) "AllgatherGlobal"> 
    <!ATTLIST MPI VerbosityLevel (0|1|2) "2">	 
    	
    <!ELEMENT ContactsParticuleObstacle EMPTY>
    <!ATTLIST ContactsParticuleObstacle Strategie (LinkedBox|LinkedCell) 
    	"LinkedCell"> 	

    <!ELEMENT Contacts (Default?, Contact*)>

    <!ELEMENT Particules (Particule+)>
      <!ELEMENT Particule (Convex, Orientation, Materiau, Couleur)>
      <!ATTLIST Particule Nombre         CDATA #REQUIRED>
      <!ATTLIST Particule MasseVolumique CDATA #REQUIRED>


    <!ELEMENT Obstacles  (Composite+)>
    <!ELEMENT Composite (Obstacle+)>
    <!ATTLIST Composite name CDATA #REQUIRED>

      <!ELEMENT Obstacle (Convex, Centre, 
                          Orientation, Materiau, Couleur)>
      <!ATTLIST Obstacle name CDATA #REQUIRED>
      <!ATTLIST Obstacle Type (Standard|Absorbant) "Standard">

    <!ELEMENT Periode (Convex, Centre, Orientation, Couleur, Vecteur)>
    <!ATTLIST Periode name CDATA #REQUIRED>

        <!ELEMENT Convex (Disque?, Box?, Polygon?)>
        <!ATTLIST Convex RayonInteraction CDATA #REQUIRED>

        <!ELEMENT Orientation (#PCDATA)>
        <!ATTLIST Orientation Type (Unite|Matrice) "Unite">

        <!ELEMENT Materiau (#PCDATA)>

        <!ELEMENT Couleur EMPTY>
        <!ATTLIST Couleur R CDATA #REQUIRED>
        <!ATTLIST Couleur V CDATA #REQUIRED>
        <!ATTLIST Couleur B CDATA #REQUIRED>

    <!ELEMENT Reload EMPTY>
    <!ATTLIST Reload Fichier CDATA #REQUIRED>
    <!ATTLIST Reload Vitesse (Reset|NoReset) "NoReset">
    <!ATTLIST Reload Type (new|same) "new"> 
    

  <!ELEMENT Forces (Gravite?, Ressort?)>
    <!ELEMENT Gravite EMPTY>
    <!ATTLIST Gravite GX CDATA #REQUIRED>
    <!ATTLIST Gravite GY CDATA #REQUIRED>
    <!ATTLIST Gravite GZ CDATA #REQUIRED>

    <!ELEMENT Ressort (Point, Raideur, Equilibre)>
      <!ELEMENT Raideur EMPTY>
      <!ATTLIST Raideur k CDATA #REQUIRED>

      <!ELEMENT Equilibre EMPTY>
      <!ATTLIST Equilibre d CDATA #REQUIRED>



  <!ELEMENT Simulation (Temps, IncreTemps, TempsSave+, Fichier,
                        Insertion?, Chargements?, PostProcessingWriters?)>
    <!ELEMENT Temps EMPTY>
    <!ATTLIST Temps Debut CDATA #REQUIRED>
    <!ATTLIST Temps Fin   CDATA #REQUIRED>

    <!ELEMENT IncreTemps EMPTY>
    <!ATTLIST IncreTemps dt (1.e-5|1.e-4|1.e-6) "1.e-5">

    <!ELEMENT AdaptationTemps EMPTY>
    <!ATTLIST AdaptationTemps Vmin CDATA #REQUIRED>
    <!ATTLIST AdaptationTemps Vmax CDATA #REQUIRED>
    <!ATTLIST AdaptationTemps C    CDATA #REQUIRED>

    <!ELEMENT TempsSave EMPTY>
    <!ATTLIST TempsSave Debut CDATA #REQUIRED>
    <!ATTLIST TempsSave Fin   CDATA #REQUIRED>
    <!ATTLIST TempsSave Dt    CDATA #REQUIRED>

    <!ELEMENT Fichier (#PCDATA)>

    <!ELEMENT Insertion (Position?, Fenetres?)>
    <!ATTLIST Insertion Methode (Preinstall|Inline)    "Inline">
    <!ATTLIST Insertion Mode    (Sequentiel|Aleatoire) "Sequentiel">
    <!ATTLIST Insertion Configuration (Fixe|Aleatoire) "Fixe">
    <!ATTLIST Insertion Frequence CDATA "1">
    <!ATTLIST Insertion Aleatoire CDATA "Reproductible">
      <!ELEMENT Position (#PCDATA)>
      <!ELEMENT Fenetres (Fenetre+)>
        <!ELEMENT Fenetre (Point, Point)>

    <!ELEMENT Chargements (Chargement+)>
      <!ELEMENT Chargement (Temps, Vecteur)>
      <!ATTLIST Chargement NomObstacle CDATA #REQUIRED>
      <!ATTLIST Chargement Mode (Translation|Rotation) "Translation">

    <!ELEMENT PostProcessingWriters (Paraview?, Visual?, GMV?, 
                                     PositionVitesse?)>
    <!ELEMENT Paraview EMPTY>
    <!ATTLIST Paraview Name CDATA #REQUIRED>
    <!ATTLIST Paraview Root CDATA #REQUIRED>
    <!ATTLIST Paraview InitialCycleNumber CDATA "0">
    <!ATTLIST Paraview Mode (text|binary) "text">
        
    <!ELEMENT Visual EMPTY>
    <!ATTLIST Visual Name CDATA #REQUIRED>

    <!ELEMENT GMV EMPTY>
    <!ATTLIST GMV Name CDATA #REQUIRED>
    <!ATTLIST GMV InitialCycleNumber CDATA "0"> 
    
    <!ELEMENT PositionVitesse EMPTY>
    <!ATTLIST PositionVitesse Name CDATA #REQUIRED>

=== anthonywachs/PacIFiC/GRAINS_V1/Main/test/2D/paroi.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Grains2D SYSTEM "../../dtd/Grains2D.dtd">

<Grains2D Type="Standard">
  <Construction>

    <Recipient LX="0.03" LY="0.05" LZ="0."/>

    <Obstacles>
      <Composite name="Boite">
	<Obstacle name="Droite">
	  <Convex RayonInteraction="1.e-5">
	    <Box LX="0.002" LY="0.10" LZ="0."/>
	  </Convex>
	  <Centre X="0.026" Y="0.05" Z="0."/>
	  <Orientation Type="Unite"></Orientation>
	  <Materiau>matO</Materiau>
	  <Couleur R="0." V="1." B=".1"/>
	</Obstacle>

	<Obstacle name="Gauche">
	  <Convex RayonInteraction="1.e-5">
	    <Box LX="0.002" LY="0.10" LZ="0."/>
	  </Convex>
	  <Centre X="0.004" Y="0.05" Z="0."/>
	  <Orientation Type="Unite"></Orientation>
	  <Materiau>matO</Materiau>
	  <Couleur R="0" V="1" B="0"/>
	</Obstacle>

	<Obstacle name="Bas0">
	  <Convex RayonInteraction="1.e-5">
	    <Box LX="0.030" LY="0.002" LZ="0."/>
	  </Convex>
	  <Centre X="0.015" Y="-.0005" Z="0."/>
	  <Orientation Type="Unite"></Orientation>
	  <Materiau>matO</Materiau>
	  <Couleur R="0." V=".75" B="0."/>
	</Obstacle>

	<Obstacle name="Bas1">
	  <Convex RayonInteraction="1.e-5">
	    <Box LX="0.010" LY="0.002" LZ="0."/>
	  </Convex>
	  <Centre X="0.015" Y="0.0005" Z="0."/>
	  <Orientation Type="Unite"></Orientation>
	  <Materiau>matO</Materiau>
	  <Couleur R="0." V=".75" B="0."/>
	</Obstacle>
      </Composite>
    </Obstacles>

  </Construction>

  <Forces>
  </Forces>

  <Simulation>

    <Temps Debut="0." Fin="1.e-5"/>
    <IncreTemps dt="1.e-5"/>
    <TempsSave Debut="0." Fin="1." Dt="0.001"/>
    <Fichier>paroi</Fichier>
  </Simulation>

</Grains2D>

=== anthonywachs/PacIFiC/GRAINS_V1/Main/test/2D/p25Move.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Grains2D SYSTEM "../../dtd/Grains2D.dtd">

<Grains2D>
  <Construction>
    <Recipient LX="0.03" LY="0.05" LZ="0.0"/>

    <Reload Fichier="p25" Vitesse="Reset"/>
  </Construction>

  <Forces>
    <Gravite GX="0." GY="9.81" GZ="0."/>
  </Forces>

  <Simulation>
    <Temps Debut="0.0" Fin="0.3"/>
    <IncreTemps dt="1.e-5"/>
    <TempsSave Debut="0.0" Fin="1.0" Dt="0.01"/>
    <Fichier>p25Move</Fichier>

    <Chargements>
      <Chargement NomObstacle="Bas1" Mode="Translation">
	<Temps Debut="0." Fin="0.25"/>
	<Vecteur X="0." Y="0.01" Z="0."/>
      </Chargement>
    </Chargements>

  </Simulation>
</Grains2D>

=== anthonywachs/PacIFiC/GRAINS_V1/Main/test/2D/periode3b.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE Grains2D SYSTEM "../../dtd/Grains2D.dtd">

<Grains2D>
  <Construction>
    <Recipient LX="0.10" LY="0.12" LZ="0.0"/>
    <Reload Fichier="periode3a" Vitesse="Reset"/>
  </Construction>

  <Forces>
    <Gravite GX="0." GY="9.81" GZ="0."/>
  </Forces>

  <Simulation>
    <Temps Debut="0." Fin="0.9"/>
    <IncreTemps dt="1.e-5"/>
    <TempsSave Debut="0." Fin="2." Dt="0.001"/>
    <Fichier>periode3b</Fichier>
  </Simulation>
</Grains2D>
